/* Recovery UI behavior only; fixture responses, no GitHub or repository writes. */
const fs=require('fs'),path=require('path'),os=require('os'),{spawn}=require('child_process');
const pw=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
const root=path.resolve(__dirname,'../../../..'),out=path.resolve(process.argv[2]);fs.mkdirSync(out,{recursive:true});
const server=spawn('python',['launch.py','--no-browser','--test-mode','--storage',fs.mkdtempSync(path.join(os.tmpdir(),'recovery-ui-'))],{cwd:root,detached:true,stdio:['ignore','pipe','pipe']});
let browser,checks=[],errors=[],stderr='';server.stderr.on('data',d=>stderr+=d);
const check=(value,label)=>{if(!value)throw Error(label);checks.push(label)};
(async()=>{
 const url=await new Promise((resolve,reject)=>{let text='';const t=setTimeout(()=>reject(Error(stderr||'startup timed out')),15000);server.stdout.on('data',d=>{text+=d;const m=text.match(/http:\/\/127\.0\.0\.1:\d+\/#[^\s]+/);if(m){clearTimeout(t);resolve(m[0])}})});
 browser=await pw.chromium.launch({executablePath:process.env.SECOND_BRAIN_BROWSER,headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1360,height:900}});page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.waitForFunction(()=>rules!==null);
 const fixture={id:'0123456789abcdef',status:'paused',title:'恢复测试（模拟界面）',organization:'Example',provider:'github',total:27,completed:27,can_resume:false,events:[],recovery:{action:'repair',title:'需要核对独立修复方案',summary:'仅处理页面列出的修复。',protected:'不会重建仓库。',steps:['核对目标','确认修复','重新核验']},repair:{id:'repair-fixture',root:'quanttide',content:'Creative Commons Attribution 4.0 International (CC BY 4.0)',created_at:'2026-09-08T00:00:00Z'},report:{provider:'github',technical_passed:false,scope:'模拟响应，不代表真实 GitHub 验收。',checked_at:'2026-09-08T00:00:00Z',rows:[{title:'远端提交是否一致',standard:'读取远端核验。',actual:'网络读取失败。',status:'unknown',source:'模拟测试',documents:[]}],failures:[{repo:'quanttide',reason:'未提交 LICENSE',status:'failed'},{repo:'quanttide-sample',reason:'连接中断',status:'unknown'}],repositories:[{name:'quanttide-sample',url:'https://github.com/Example/quanttide-sample',status:'unknown',checked_at:'2026-09-08T00:00:00Z'}]}};
 await page.evaluate(()=>{view={status:'paused',has_plan:false,total:0,completed:0,events:[],can_resume:false,error:'暂时无法读取章程',recovery:{action:'retry-plan',title:'尚未形成创建方案',summary:'尚未写入。',protected:'填写内容已保留。',steps:['重新生成方案','核对新方案','人工确认']}};render()});
 check(!(await page.locator('#repair-panel').isVisible()),'Planning failure hides unrelated LICENSE recovery panel');
 check(!(await page.locator('#resume').isVisible()),'Planning failure does not offer execution resume');
 check(await page.locator('#retry-plan').isVisible(),'Planning failure offers only plan regeneration');
 check((await page.locator('#recovery-card').textContent()).includes('人工确认'),'Recovery card explains the complete next path');
 await page.evaluate(()=>{view={status:'paused',has_plan:true,provider:'github',total:27,completed:27,events:[],can_resume:false,error:'最终检查尚未生成',recovery:{action:'verify',title:'创建步骤已保存',summary:'只需重新核验。',protected:'不会重复写入。',steps:['重新检查最终结果']}};render()});
 check(await page.locator('#paused-reverify').isVisible(),'Completed paused run exposes final recheck without prior report');
 check(!(await page.locator('#repair-panel').isVisible()),'Completed run without LICENSE evidence hides unrelated repair');
 await page.evaluate(()=>{view={status:'paused',has_plan:true,legacy_partial:true,total:27,completed:4,events:[],can_resume:false,error:'旧任务待核对',recovery:{action:'partial',title:'旧任务待核对',summary:'检查接续凭证。',protected:'原记录不改写。',steps:['检查接续方案']},partial_proposal:{id:'fixture',organization:'Example',repo:'test',repository_id:123,commit:'abc',checked_at:'2026-09-09',content:'# test'}};render()});
 check(await page.locator('#partial-panel').isVisible(),'Legacy partial run exposes reviewed adoption panel');
 check((await page.locator('#partial-content').textContent()).includes('123'),'Adoption displays stable repository identity');
 let partialWrites=0;await page.route('**/api/runs/*/partial-apply',r=>{partialWrites++;return r.fulfill({json:{}})});
 await page.locator('#partial-apply').click();check(partialWrites===0,'Adoption requires explicit confirmation');
 let writes=0;
 await page.route('**/api/runs/0123456789abcdef/repair-apply',r=>{writes++;return r.fulfill({json:{id:fixture.id}})});
 await page.route('**/api/runs/0123456789abcdef',r=>r.fulfill({json:fixture}));
 await page.evaluate(f=>{current=f.id;view=f;render()},fixture);
 check((await page.locator('#technical-status').textContent()).includes('1 项发现问题，1 项暂时无法核验'),'Unavailable observations are separate from actual defects');
 check((await page.locator('#failure-reasons').textContent()).includes('quanttide-sample'),'Failure details identify repository');
 check((await page.locator('#report-rows').textContent()).includes('暂时无法核验'),'Requirement row preserves unknown state');
 check((await page.locator('#repair-content').textContent()).includes('CC BY 4.0'),'Repair displays proposed license content');
 await page.locator('#repair-apply').click();check(writes===0,'No repair request without explicit confirmation');
 await page.locator('#repair-confirmed').check();await page.locator('#repair-apply').click();await page.waitForFunction(()=>!busy);check(writes===1,'Confirmed repair sends exactly one request');
 let checksRequested=0;await page.route('**/api/runs/0123456789abcdef/connection-check',r=>{checksRequested++;fixture.connection_check={checks:[{label:'账号接口',status:'passed'},{label:'远端版本',status:'unknown',reason:'模拟断网'},{label:'下载连接',status:'unknown',reason:'模拟断网'}]};return r.fulfill({json:{id:fixture.id}})});
 await page.locator('#connection-check').click();await page.waitForFunction(()=>!busy);check(checksRequested===1,'Connection check has a dedicated read-only action');check((await page.locator('#connection-results').textContent()).includes('模拟断网'),'Connection channels display separate results');
 await page.evaluate(()=>returnToForm(false));check(await page.locator('#connection-check').isDisabled(),'Connection check is disabled when no run is open');await page.evaluate(f=>{current=f.id;view=f;render()},fixture);
 await page.screenshot({path:path.join(out,'repair-desktop.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Paused repair screen fits mobile viewport');
 await page.screenshot({path:path.join(out,'repair-mobile.png'),fullPage:true});check(errors.length===0,'No JavaScript errors');
 fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'passed',at:new Date().toISOString(),checks,errors,platform:process.platform,github:'simulated',real_windows:false},null,2));console.log(JSON.stringify({status:'passed',checks:checks.length}));
})().catch(e=>{fs.writeFileSync(path.join(out,'result.json'),JSON.stringify({status:'failed',error:String(e),checks,errors},null,2));console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();try{process.kill(-server.pid,'SIGTERM')}catch{}});
